### ISSUE TITLE
OpenCore is called a "rootkit" on the guide.

### ISSUE THREAD

**Issue by RandoNandoz** [dortania/OpenCore-Desktop-Guide#35]
"OpenCore is an open-source, unconventional, first-in-class piece of software designed to intercept kernel loading to insert a highly advanced rootkit, designed to be an alternative to Clover." is found on the first paragraph of the introduction.

A rootkit is a piece of malware, and advertising OpenCore as a piece of malware doesn't seem prudent. Perhaps a bootloader?

**Comment by khronokernel** [comment]
Well boot.efi is the real boot loader, and OpenCore(Clover and others as well) inject data and patch various things to prepare for it. So it is in fact a rootkit.

Rootkits are not inherently malware, plenty of DRM and security software would be seen as malware as well then. But I needed to rewrite the introduction anyways as it's a bit clunky, and I suppose most users don't actually understand there's "good" rootkits as the media mainly talks about them in a negative connotation.

Fixed in this commit: 54e3729
