### ISSUE TITLE
some feedbacks

### ISSUE THREAD

**Issue by fredsky2003** [dortania/OpenCore-Desktop-Guide#42]
hello !
i'm a little new to OpenCore, i've sucessfully installed ryzentosh with OC 0.5.7 and updated with 0.5.8

1) please add back the links to the GPU and wireless buyers guides... i mean those first links : https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/ , but on the  new one : https://dortania.github.io/OpenCore-Desktop-Guide/

2) during my first install I lost many hours with random issue during boot, because in BIOS sata must be set with hotplug DISABLE !!!! add this trick to the BIOS section.

3) ACPI, with 0.5.8 guide it is confusing, because :
a)https://dortania.github.io/OpenCore-Desktop-Guide/ktext.html 
at the end you have a table of ACPI, which is NOT present into the dedicated ACPI guide.
it should be there https://dortania.github.io/Getting-Started-With-ACPI/ssdt-easy.html
b) please precise that for Zen CPU you do need 2 files : SSDT-EC-USBX-DESKTOP.aml and SSDT-USBX.aml into OC/ACPI folder

4) add again this link as conclusion of all ACPI pages/sections to the wonderfull tool Sanity Checker
https://opencore.slowgeek.com/
add it also at then end of "updating opencore" section : https://dortania.github.io/OpenCore-Desktop-Guide/post-install/update.html ; because is a "life saver" to help checking if config.plist is updated correctly :)

keep up this EXCELLENT work! a true revolution of the hackintosh world!

regards,
fred

**Comment by khronokernel** [comment]
> please add back the links to the GPU and wireless buyers guides... i mean those first links : https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/ , but on the new one : https://dortania.github.io/OpenCore-Desktop-Guide/

We have the [Dortania home page](https://dortania.github.io/getting-started/), though I suppose we can add a link to that on the front

> at the end you have a table of ACPI, which is NOT present into the dedicated ACPI guide.
it should be there https://dortania.github.io/Getting-Started-With-ACPI/ssdt-easy.html

It is there, second page: [What SSDTs do each platform need](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html)

> during my first install I lost many hours with random issue during boot, because in BIOS sata must be set with hotplug DISABLE !!!! add this trick to the BIOS section.

Could you elaborate on "issues" as if we want to add it to the troubleshooting page, we need to first have an obvious area where this would be needed(ie. Drive missing in Disk Utility)

> please precise that for Zen CPU you do need 2 files : SSDT-EC-USBX-DESKTOP.aml and SSDT-USBX.aml into OC/ACPI folder

You don't... SSDT-EC-USBX-DESKTOP already has USBX inside it, even in the name

> add again this link as conclusion of all ACPI pages/sections to the wonderfull tool Sanity Checker
https://opencore.slowgeek.com/
add it also at then end of "updating opencore" section : https://dortania.github.io/OpenCore-Desktop-Guide/post-install/update.html ; because is a "life saver" to help checking if config.plist is updated correctly :)

Well the main problem is the sanity tool isn't always on the latest release(as it's not maintained by the Dortania organization), so relying on it is up to the user. Though still adding a link with a warning isn't too bad of an idea

**Comment by fredsky2003** [comment]
hello ! 
thanks for the quick reply

> We have the Dortania home page, though I suppose we can add a link to that on the front
haha this is the first time i'm seeing this page, since i always go/find the "desktop" guide. so yes please add a link to Home on each sub guides.

for ACPI. what i means it that yes i know this table link, but no it is not present of the dedicated section : https://dortania.github.io/Getting-Started-With-ACPI/ssdt-easy.html
please add it.

> Could you elaborate on "issues" as if we want to add it to the troubleshooting page, we need to first have an obvious area where this would be needed(ie. Drive missing in Disk Utility)
it's easy. if in the BIOS SATA is configured with hotplug enabled, then during boot it will either freeze/stuck (stay in console mode) or go normally. when you change to SATA hotplug disabled, then boot goes perfect each time.

> SSDT-EC-USBX-DESKTOP
ok it's because i got the old SSDT-USBX.aml of 0.5.7 and the sanity checker told that i should add the Destop one too. but yes infact keeping only DESKTOP does work and is approuved by Sanity

> Well the main problem is the sanity tool isn't always on the latest release(as it's not maintained by the Dortania organization), so relying on it is up to the user. Though still adding a link with a warning isn't too bad of an idea
it should be, at it is very nice, and updated. you can even choose the version and plateform :)

regards,
fred

**Comment by khronokernel** [comment]
Should all be addressed in master, ssd-easy table I've decided not to include as to not bloat the pages with repetitive info
