### ISSUE TITLE
Hope you to add a guide category for this platform

### ISSUE THREAD

**Issue by lgq163** [dortania/OpenCore-Desktop-Guide#45]
mainboard: asrock rack ep2c621d12ws, intel c621 chipset, dual sockets
cpu: intel xeon platinum 8175M x2, 2.5GHz, 48Cores, 96Threadings, Skylake Server, Cpuid: 0x50654
gpu: Nvidia Quadro P5000
    I have tried for almost 6 months. I want to install MacOS X 10.13.6.  It's not like skylake nor skylake-x in this guide.

**Comment by khronokernel** [comment]
Skylake SP, W and X are all bundled together in the guide, if there's any direct issues with our guide regarding support I'm more than happy to add it. But we don't have the hardware personally, and very few users do so giving resources into that instead of other projects wouldn't be all too beneficial. Gonna close this issue for now, but I you do have any suggestions I'm more than happy to add them
