### ISSUE TITLE
iServices Customer Code error fixed without calling Apple Support

### ISSUE THREAD

**Issue by lese123** [dortania/OpenCore-Desktop-Guide#46]
I encounter the customer code error while trying to log into iMessages and was given a code and asked to contact Apple support. I used GenSMBIOS to inject Platform information into my config.plist. Checked on Apple Check Coverage and it said "We’re sorry, but this serial number isn’t valid. Please check your information and try again." Same error happened with a newly created AppleID on the same computer. I could not use iMessages and FaceTime, but Music, App Store, iCloud worked fine.

The Open Desktop Guide says "The fix is simple but not pretty, you MUST call Apple. Otherwise, there is no proceeding besides using a new account."

Switching AppleID or invalid serials did not work. I did not call Apple Support but instead using iMessageDebug to get information from an unused MacBook Pro and injected the SMBIOS (serial, MLB, UUID, ROM) from the MacBook Pro to my Hackintosh computer. This fixed it and I could immediately use iMessages, FaceTime.

This proved that this customer code error may be related to randomly generated SMBIOS information not being recognized by Apple for iMessages and FaceTime and has nothing to do with blacklisted AppleID. I'm not sure if it is a new Apple policy so probably more tests are needed.

**Comment by 1Revenger1** [comment]
We recommend using an unused serial because if you use a serial from a working mac, you can get working iServices. But you end up likely screwing both of you up because two devices are using the same serial with different ROM or other values.
It's fine if it's your device and you aren't using it, but we recommend randomizing to reduce the chance of screwing other people.
Usually when you use a random serial it's not registered as an actual device, and so you need to call apple to get it registered for iServices to work. It can work without needing to call them if you randomize, but their algorithm is weird and often times having other apple products beforehand can help. No one really understands how it works though, so the best we can do is make educated guesses.

**Comment by lese123** [comment]
Thanks for the clarification. Now I see that calling Apple support is actually for adding the randomized SMBIOS to the Apple database so that iServices can be used. The fact that I could use iCloud showed that it was not that my AppleID was blacklisted but my Hackintosh information was not registered in the Apple database. Just creating a new AppleID does not help.

**Comment by khronokernel** [comment]
Closing as offtopic, can comment if there's something to contribute to the guide
