### ISSUE TITLE
[SUGGESTION] USB Mapping guide

### ISSUE THREAD

**Issue by dreamwhite** [dortania/OpenCore-Desktop-Guide#5]
In your [guide](https://dortania.github.io/OpenCore-Desktop-Guide/post-install/usb.html#intel-usb-mapping) is mentioned `USBMap` mapping procedure as it's more easier to use for non-skilled users etc. As @Gengik84 suggested in his [forum thread](https://www.macos86.it/topic/9-mappatura-porte-usb/page/1) (sorry for italian language, can read an english version [here](https://utopiateam.gitbook.io/mammamia-marcello-vanilla-guide/usb/mapping/intel)). What do you think about? Is the ACPI version "easier"? 
Thanks

**Comment by midi1996** [comment]
The same script can also generate UIAC SSDT, the thing is, we're trying to move away from USBInjectAll since it requires to be updated with each mac release and macOS version, also you're adding another resource that eats memory (by today's standards, it's not even considered that much). However USBInjectAll really just does what macOS do already and even more aggressively when it forces showing all possible entries of each personality. So we chose the codeless kext method of using a USBMap.kext that would actually just use your SMBIOS + XHCI name and add the ports which is how macOS drivers actually enumerates and limits the ports, no need for any external code. This also makes it update-resistant which helps with macOS updates that would break USBInjectAll (not that I saw that happen, but you never know what can apple do).

**Comment by dreamwhite** [comment]
Well, wait... I said in the guide that USBInjectAll isn't needed but in the last hackintoshes I've tried mapping without USBInjectAll and it still works. Don't know if it's the same. Also USBMap requires USBInjectAll as first step. I don't know where is the problem :/

**Comment by midi1996** [comment]
Yes this is an ACPI thing. Some OEMs will map all their kexts in their ACPI and macOS would enumerate everything as describes the ACPI, but also some computers happen to have their XHCI device in ACPI named the same way as their SMBIOS (say for example your ACPI has XHC1 and the native macOS kext has already that SMBIOS with a map for XHC1), and thus they either have to rename or use USBInjectAll or both. Also, the reason why we're using it is to standardize the detection method (since looking for the USB Port map in ACPI can wildly vary from a device to device (some are in DSDT, some in some SSDT, and some are all over the place). So we're trying to use USBInjectAll just as a temporary helper. I might actually update the guide to get the info from windows (idk how to do that on linux, but will probably find a way). Your case might be a lucky one (and I've seen many of those, it's not uncommon).

**Comment by dreamwhite** [comment]
Well, usually USB ports on recent hardware (not the IBM 9000 e.g.) are commonly defined inside SSDT or DSDT. What changes between them is only the step about dropping the SSDT table, which isn't required if USB ports are defined inside DSDT. 


> say for example your ACPI has XHC1 and the native macOS kext has already that SMBIOS with a map for XHC1), and thus they either have to rename or use USBInjectAll or both

Can you explain better this phrase? What you mean? If the XHCI controller name is the same as macOS wants, and e.g. there's a mapping for the SMBIOS with the map for XHCI, you need to rename it? Why? I'm feeling a little bit confused haha

Many thanks for replying btw

**Comment by midi1996** [comment]
If your XHCI device name is the same as the one macOS looks for (with the same SMBIOS you're using) it will usually map and limit the ports according to what the internal kext has. So basically we're just preventing it from doing that by renaming the ACPI device name, map it and use a codeless kext to override that built-in mapping.

**Comment by dreamwhite** [comment]
> If your XHCI device name is the same as the one macOS looks for (with the same SMBIOS you're using) it will usually map and limit the ports according to what the internal kext has. So basically we're just preventing it from doing that by renaming the ACPI device name, map it and use a codeless kext to override that built-in mapping.

Uhm... but wait, if you use USBInjectAll as a custom injector, then map again the USBs what changes? For example my XHC controller is named `XHC` without need of renaming it through Clover or ipotetically on OpenCore. I'm using as SMBIOS `MacbookPro15,2` and the Apple USB kext has already a map for it. Below a screenshot of my IORegistryExplorer report. 
![image](https://user-images.githubusercontent.com/17933708/79570335-8a8ca680-80b9-11ea-976c-dd4ccff77d98.png)
`USBInjectAll` kext was used only for the first mapping step, namely injecting all the ports, then immediately removed. What do you think about it? 
Thanks

**Comment by midi1996** [comment]
ok so here is the thing, if you check `/System/Library/Extensions/IOUSBHostFamily.kext/Contents/PlugIns/AppleUSBHostPlatformProperties.kext/Contents/Info.plist` you'll find a lot of premade patches by apple for their devices. and here is how our mapping works:
1. Get the USB ports (all of them)
 * rename XHC if needed
 * USBInjectAll (as the name suggests) will inject every possible port in the system
2. Use USBMap to cherry pick the USB that you want to use
3. Map them by type
4. Get a codeless kext
5. Remove USBInjectAll and Add the new USB Map kext
6. You'll get your USBs Mapped by native solutions.

**Comment by midi1996** [comment]
In your case MBP15,x does not have any map provided by apple (since they're not using the PCH's XHCI controller but the TB3 controllers). So whatever it's named, it will work just fine (I guess). But at that point it's all about how your ACPI ports are laid out. This could be also why some people (like my P50) have only 5 ports on HSP showing and 5 ports on SSP showing without USBInjectAll, and also (like my X2) have all my ports already pre-mapped by the OEM (didnt really need to map anything at all) or some others (like desktop motherboards) where their ACPI already laids everything to the OS and need to be mapped.

**Comment by dreamwhite** [comment]
That's really interesting, need to investigate about it. Do you have any useful resource eventually?

**Comment by midi1996** [comment]
USBInjectAll, USBMap and the USB drivers of macOS are the source. There are also links to other forums in those repos.
